--- # Playbook to install rsnapshot backup tool
- hosts: "{{ hosts }}"
  remote_user: "{{ user }}"
  become: yes
  become_method: sudo
  gather_facts: yes
  connection: ssh
  vars_files:
    - credentials.yml
    - config_vars.yml
    - aws_config_vars.yml
  roles:
    - awscli
    - s3-bucket
