- name: Install rsnapshot dependencies
  apt: name={{ item }} state=latest
  with_items:
    - liblchown-perl
    - logrotate
    - perl
    - rsync
    - openssh-client
  tags:
    - install

- name: Install rsnapshot from apt repository
  apt: name=rsnapshot state=latest
  notify:
    - Confirm that config file exists
    - rsnapshot error message
  tags:
    - install

### MYSQL CONFIGURATION BLOCK ###

- include: mysql.yml

### TEST CONFIGURATION ###

- name: Test if configuration was successful
  command: bash -c "rsnapshot configtest"
  register: config_test
  tags:
    - configuration-test

- name: Fail if configuration is not successful
  fail: msg="rsnapshot configuration was not successful"
  when: config_test|failed
  tags:
    - configuration-test

### TEST BACKUP COMMAND MANUALLY ###

- include: backup.yml


### AUTOMATE BACKUP PROCESS ###

- include: cron.yml

